name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Security Quality Gates (Snyk + Trivy + SonarCloud)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Snyk scan
        uses: snyk/actions/python@master
        with:
          command: test
          args: "--file=requirements.txt --severity-threshold=medium"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy FS scan (fail on HIGH, CRITICAL)
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Run Trivy config scan (fail on HIGH, CRITICAL)
        run: trivy config --exit-code 1 --severity HIGH,CRITICAL .

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=wilsondala_aws-devsecops-pipeline-demo
            -Dsonar.organization=wilsondala
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
